#!/usr/bin/env python

from __future__ import print_function
import string

def isprintable(x):
  return x in string.printable

def toprintable(x):
  return filter(isprintable, x)

import sys

atStart = True
inInput = True
postBlock = False
for line in sys.stdin:
  if len(line) > 0 and not isprintable(line[0]):
    continue
  if line.startswith('# In['):
    inInput = True
    postBlock = True
    continue
  if line.startswith('# Out['):
    inInput = False
    postBlock = True
    continue
  if not inInput:
    continue
  if line.startswith('# noexport'):
    inInput = False
    continue
  if postBlock:
    postBlock = False
    continue
  if atStart:
    if line.strip() == '':
      continue
    else:
      atStart = False
  print(line, end='')
